Add chaussures with price range and fees
scopyleft/douane pull request #30
Opened 2017-02-10 21:51 UTC by davidbgk

2017-02-10 22:08 UTC, vinyll requested changes
additionné**s** est en référence au document ods fournis.
Impacte les autres pages aussi.

2017-02-10 22:08 UTC, vinyll commented on chaussures/index.html
> +      <li>soumise à une TVA de 20 % sur le prix du produit additionné des frais supplémentaires éventuels.</li>
additionné**s**

2017-02-10 22:08 UTC, vinyll commented on chaussures/index.html
> +      La réception de chaussures achetés hors Union européenne est :
acheté**e**s

2017-02-10 22:08 UTC, vinyll commented on chaussures/index.html
> +    Cette réponse est valable pour l’achat de chaussures, achetés hors Union européenne, et dont le prix affiché, y compris les frais supplémentaires, est de {formatNum(calculator.amountWithShipping(
acheté**e**s

2017-02-10 22:08 UTC, vinyll commented on chaussures/index.html
> +      La réception de chaussures achetés hors Union européenne est :
acheté**e**s

2017-02-10 22:08 UTC, vinyll commented on chaussures/index.html
> +    Cette réponse est valable pour l’achat de chaussures, achetés hors Union européenne, et dont le prix affiché, y compris les frais supplémentaires est de {formatNum(calculator.amountWithShipping()
acheté**e**s

2017-02-10 22:08 UTC, vinyll commented on chaussures/index.html
> +      La réception de chaussures achetés hors Union européenne est :
acheté**e**s

2017-02-10 22:08 UTC, vinyll commented on chaussures/index.html
> +      <li>soumise à une TVA de 20 % sur le prix du produit additionné des frais supplémentaires et des droits de douane éventuels.</li>
additionné**s**

2017-02-10 22:11 UTC, vinyll commented
Je vois qu'on utilise l'ancienne forme de coûtera. Il faudrait homogénéiser le terme dans les différentes pages.

2017-02-10 22:43 UTC, davidbgk commented
@vinyll pour le additionné, je propose de le garder sans le s vu qu'il a été enlevé via https://github.com/scopyleft/douane/pull/29

2017-02-11 15:46 UTC, vinyll approved these changes

2017-02-11 16:22 UTC, merged