Implement perfumes
scopyleft/douane pull request #8
Opened 2016-09-30 02:19 UTC by davidbgk

2016-09-30 06:47 UTC, vinyll requested changes

2016-09-30 06:47 UTC, vinyll commented on perfumes/index.html
> +<!DOCTYPE html>
quid perfumes vs parfums.
Je comprend qu'ils aient choisi le singulier uniformément mais là, ca fait bizarre, non ?

2016-09-30 06:47 UTC, vinyll commented on perfumes/index.html
> +  <h1>Bienvenue sur le prototype de « Calcul des taxes et droits de douane » pour estimer le montant des droits à payer pour l’achat en ligne de parfum et d’eau de toilette.</h1>
_parfums et eaux de toilette_ ?

2016-09-30 06:47 UTC, vinyll commented on perfumes/index.html
> +    Cette réponse est valable pour l’achat <em>du parfum ou d’eau de toilette</em>, acheté dans un pays de l'Union européenne, et dont le prix est <strong>{calculator.amount} Euros</strong> <abbr tit
_du parfum ou d’eau de toilette_ vs _d'un parfum ou d’une eau de toilette_

2016-09-30 06:47 UTC, vinyll commented on perfumes/index.html
> +<script>
déplacer dans un fichier JS partagé, à l'instar du CSS, plutôt que de dupliquer.

2016-09-30 13:00 UTC, davidbgk commented on perfumes/index.html
> +<!DOCTYPE html>
Tu parles de anglais/français ou singulier/pluriel ? C'est pas super clair pour moi. Le mieux serait certainement de demander au client, ou encore mieux aux utilisateurs ;)

2016-09-30 13:05 UTC, davidbgk commented on perfumes/index.html
> +<script>
Ce n'est pas tout à fait le même JS car le produit change dans les traces. Je propose de laisser ainsi pour l'instant, de voir comment ça évolue et de factoriser lors de l'ajout d'un troisième produit.

2016-09-30 13:32 UTC, vinyll commented on perfumes/index.html
> +<script>
mhhh… Je mettrai mes manies de côté et j'hypothèserai qu'on le refactorise dans la foulée

2016-09-30 13:34 UTC, vinyll commented on perfumes/index.html
> +<!DOCTYPE html>
quid du en/fr

2016-09-30 14:45 UTC, raphaelpierquin commented on perfumes/index.html
> +<!DOCTYPE html>
je préfère en français (pour cohérence avec le nom de domain). Mais cela n'a probablement pas d'importance à ce stade.

2016-09-30 17:37 UTC, davidbgk commented on perfumes/index.html
> +<!DOCTYPE html>
@raphaelpierquin mais du coup telephones/parfums ? ça fait bizarre car dans le texte on emploie le terme *smartphone* ensuite…

2016-10-04 08:33 UTC, raphaelpierquin commented on perfumes/index.html
> +<!DOCTYPE html>
... c'est pas bizarre si on considère que "smartphone" est un mot français.

2016-10-06 20:09 UTC, vinyll commented
r+ avec amélioration en prochaine release ;)

2016-10-06 20:09 UTC, vinyll approved these changes

2016-10-07 01:21 UTC, merged